authapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('', authapp.MainTemplateView.as_view(), name='main'),
    path('sign_in/', authapp.sign_in, name='sign_in'),
    path('sign_up/', authapp.sign_up, name='sign_up'),
    path('sign_out/', authapp.sign_out, name='sign_out'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify'),
]

test_task/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authapp.urls', namespace='auth')),
    path('load_data/', mainapp.load_data, name='load_data'),
    path('show_required_analyzes/<int:pk>/', mainapp.show_required_analyzes, name='show_required_analyzes'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now
from datetime import timedelta


class Doctor(AbstractUser):

    MALE = 'М'
    FEMALE = 'W'

    GENDER_CHOICES = (
        (MALE, 'M'),
        (FEMALE, 'W')
    )

    SURGEON = 'SURGEON'
    ONCOLOGIST = 'ONCOLOGIST'
    THERAPIST = 'THERAPIST'

    PROFESION_CHOICES = (
        (None, 'Select your profession'),
        (SURGEON, 'Surgeon'),
        (ONCOLOGIST, 'Oncologist'),
        (THERAPIST, 'Therapist'),
    )

    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveSmallIntegerField(default=18)
    email = models.EmailField(max_length=150, unique=True)
    profession = models.CharField(max_length=32, choices=PROFESION_CHOICES)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)

    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(default=(now() + timedelta(hours=48)))

    class Meta:
        verbose_name = 'doctor'
        verbose_name_plural = 'doctors'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def is_activation_key_expired(self):
        if now() <= self.activation_key_expires:
            return False
        else:
            return True

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import Doctor
from django import forms
import hashlib
from random import random


class DoctorSignInForm(AuthenticationForm):

    class Meta:
        model = Doctor
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = "form-control"
            field.help_text = ''
            field.error_messages['required'] = ''


class DoctorSignUpForm(UserCreationForm):
    class Meta:
        model = Doctor
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2',
                  'email', 'avatar', 'age', 'gender', 'profession')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = "form-control"
            field.help_text = ''
            field.error_messages['required'] = ''

    def save(self, **kwargs):
        doctor = super().save()
        doctor.is_active = False
        salt = hashlib.sha1(str(random()).encode('utf8')).hexdigest()[:6]
        doctor.activation_key = hashlib.sha1((doctor.email + salt).encode('utf8')).hexdigest()
        doctor.save()

        return doctor

authapp/views.py
from django.shortcuts import render

from authapp.forms import DoctorSignInForm, DoctorSignUpForm
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic.base import TemplateView
from smtplib import SMTPDataError
from authapp.models import Doctor


class MainTemplateView(TemplateView):
    template_name = 'authapp/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'main'
        return context_data


def verify(request, email, activation_key):
    """Perform user verification."""

    try:
        user = Doctor.objects.get(email=email)
        if user.activation_key == activation_key and not user.is_activation_key_expired():
            user.is_active = True
            user.save()
            auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            print('activation was successful')
        else:
            print(f'user activation error: {email}')
        return render(request, "authapp/verification.html")
    except Exception as e:
        print(f'user activation error: {e.args}')
        return HttpResponseRedirect(reverse('authapp:main'))


def send_verify_email(user):
    """Send an email for user verification."""

    verify_link = reverse('authapp:verify', args=[user.email, user.activation_key])
    subject = f'user activation {user.username}'
    message = f'to confirm, follow the link: {settings.DOMAIN_NAME}{verify_link}'
    try:
        return send_mail(subject, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=False)
    except SMTPDataError:
        pass


def sign_in(request):
    title = "sign in"
    next_url = request.GET.get('next', '')
    login_form = DoctorSignInForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('authapp:main'))
    from_register = request.session.get('register', None)
    conf_code = request.session.get('conf_code', None)
    email = request.session.get('email', None)
    if from_register:
        del request.session['register']
        del request.session['conf_code']
        del request.session['email']

    content = {
        'title': title,
        'login_form': login_form,
        'next': next_url,
        'from_register': from_register,
        'confirmation': conf_code,
        'pth': f'{settings.DOMAIN_NAME}{request.get_full_path()}{email}{conf_code}',
        'email': email
    }
    return render(request, 'authapp/sign_in.html', content)


def sign_up(request):
    title = 'sign up'

    if request.method == 'POST':
        register_form = DoctorSignUpForm(request.POST, request.FILES)

        if register_form.is_valid():
            user = register_form.save()
            if send_verify_email(user):
                print('confirmation message sent')
                request.session['register'] = True
                user_name = request.POST['username']
                conf_code, email = [Doctor.objects.get(username=user_name).activation_key,
                                    Doctor.objects.get(username=user_name).email]
                request.session['conf_code'] = conf_code
                request.session['email'] = email

            else:
                print('error sending the message')
            return HttpResponseRedirect(reverse('authapp:sign_in'))

    else:
        register_form = DoctorSignUpForm()
    content = {
        'title': title,
        'register_form': register_form,
    }
    return render(request, 'authapp/sign_up.html', content)


def sign_out(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('authapp:main'))

authapp/templates/authapp/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/authapp.css' %}">
    {% endblock %}
    {% block js %}
        <script
          src="https://code.jquery.com/jquery-3.6.0.min.js"
          integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
          crossorigin="anonymous"></script>
        <script src = "{% static 'js/patient_script.jsx' %}"></script>
    {% endblock %}
</head>
<body>
    <div>
            {% block content %}
			{% endblock %}
    </div>
</body>
</html>

authapp/templates/authapp/index.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    {% if user.is_authenticated %}
        <h2>Hello, {{ user.username }}</h2>
        <button>
            <a style='text-decoration: none; color: #1b1b1b' href="{% url 'auth:sign_out' %}">Sign out</a>
        </button>
        <button>
            <a style='text-decoration: none; color: #1b1b1b' href="{% url 'load_data' %}">Load data</a>
        </button>
    {% else %}
        <button>
            <a style='text-decoration: none; color: #1b1b1b' href="{% url 'auth:sign_in' %}">Sign in</a>
        </button>
        <button>
            <a style='text-decoration: none; color: #1b1b1b' href="{% url 'auth:sign_up' %}">Sign up</a>
        </button>
    {% endif %}
{% endblock %}

authapp/templates/authapp/sign_in.html
{% extends 'authapp/base.html' %}
{% block content %}
    {% if from_register %}
        Confirmation message sent.<br>
        Confirmation code: {{ confirmation }}<br>
        Link to go to: <a href="{% url 'authapp:verify' email  confirmation %}">{{ pth }}</a><br>
        The confirmation email was saved in the path: <strong>tmp/email-messages.</strong>
    {% endif %}
    <form action="{% url 'auth:sign_in' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% if next %}
        <input name="next" type="hidden" value="{{ next }}" />
    {% endif %}
    {{ login_form.as_p }}
    <br>
    <button style='cursor: pointer;' type="submit">Sign in</button>
    </form>
    <button>
        <a style='text-decoration: none; color: #1b1b1b' href="{% url 'auth:sign_up' %}">Sign up</a>
    </button>
{% endblock %}

authapp/templates/authapp/sign_up.html
{% extends 'authapp/base.html' %}
{% block content %}
    <form action="{% url 'auth:sign_up' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ register_form.as_ul }}
    <br>
        <button style='cursor: pointer;' type="submit" >Sign Up</button>
    </form>
    <button>
        <a style='text-decoration: none; color: #1b1b1b' href="{% url 'auth:sign_in' %}">Sign in</a>
    </button>
        <div>{{ message }}</div>
        <div>{{ conf_code }}</div>
{% endblock %}

authapp/templates/authapp/verification.html
{% extends 'authapp/base.html' %}
{% block content %}
  {% if user.is_authenticated %}
    <h3>Congratulate!</h3>
    <br>
    <h4>User {{user.username}} has been confirmed.</h4>
  {% else %}
    <h3>Verification failed.</h3>
  {% endif %}
  <br>
  <button>
    <a style='text-decoration: none; color: #1b1b1b' href="{% url 'authapp:main' %}">To the main page</a>
  </button>
{% endblock %}